// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIxE2gjOV18Wn37XKiWWZK5q1caO3v1-k',
    appId: '1:399238685035:web:ca1600181d85d61619ec2e',
    messagingSenderId: '399238685035',
    projectId: 'spotify-813fc',
    authDomain: 'spotify-813fc.firebaseapp.com',
    storageBucket: 'spotify-813fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq8lRgRCeWSg_RcvwmClWrLErR0cgyGIM',
    appId: '1:399238685035:android:2be923064118bcc419ec2e',
    messagingSenderId: '399238685035',
    projectId: 'spotify-813fc',
    storageBucket: 'spotify-813fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA1OxncbPluulrvBz--P_Rw3CPRJp40Co',
    appId: '1:399238685035:ios:90b9ac0ca8205b9719ec2e',
    messagingSenderId: '399238685035',
    projectId: 'spotify-813fc',
    storageBucket: 'spotify-813fc.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );
}
